version: '3.9'
services:
  frontend:
    container_name: sharenergy_frontend
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_HOST=localhost:3001
      - REACT_APP_API_PROTOCOL=http
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: sharenergy_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_HOST=db
      - DB_PORT=27017
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mongo
    container_name: sharenergy_db
    platform: linux/x86_64
    ports:
      - 3002:27017
    restart: 'always'
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s